language: php

services:
   - docker

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - docker run -d -p 127.0.0.1:8081:8080 -e "MB_KEY=M2JjMjZjMzdhMDRlYzU3MWZiZDc3MDBmODE0ZTNmNmQ.vb4Zy2z028B125tFoMj9JPQlj8gEtk5HxatAf5YDUut-W6TcSHhIIPHAmSxVhNeSYvBl1M5pE4BJCCC5oFcSvg" machinebox/classificationbox:latest
  - docker ps -a

install:
  - composer remove --no-update --no-scripts --dev andreaskasper/machinebox-php
  - composer install
  
#script: ./vendor/bin/phpunit --configuration ./travis.phpunit.xml.dist
  
stages:
  - coding-standard
  - test

jobs:
  include:
    - stage: coding-standard
      before_install:
      before_script:
      after_script:
      php: 5.5
      env: CS_CHECK=1
    - stage: test
      php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: hhvm
      dist: trusty